version: '3.8'

services:
  part5_container:
    build: ../05
    container_name: fcgi-server
  nginx:
    image: nginx:latest
    container_name: proxy-server
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:8080" # Маппинг порта 8080 второго контейнера на порт 80 локальной машины